[package]
name = "rust-api-101"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"

[[bin]]
name = "rust-api-101"
path = "src/main.rs"
